import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.support.AnnotationConfigContextLoader;

import static org.junit.Assert.*;

import java.math.BigDecimal;

import org.avci.flower.Flower;
import org.avci.flower.FlowerRepo;
import org.avci.flower.FlowerService;
import org.avci.util.FlowerAppConfig;
import org.avci.util.MongoConfig;
import org.avci.util.MongoConfig1;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'OA10249' at '3/22/16 5:00 PM' with Gradle 2.11
 *
 * @author OA10249, @date 3/22/16 5:00 PM
 */

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { MongoConfig.class, FlowerAppConfig.class } )
public class FlowerServiceTest {

@Autowired
FlowerRepo repo;

private final Logger logger = LoggerFactory.getLogger(FlowerServiceTest.class);

	
@Autowired
FlowerService flowerService;

    @Test public void testAddFlower() {
        //FlowerService classUnderTest = new FlowerService();
        Flower f = new Flower();
        f.setDescription("TestFlower Desc");
        f.setFlowerImageUrl("null");
        f.setName("testFlower");
        assertTrue("Add flower should return id", flowerService.addFlower(f).getId()!=null);
        logger.debug("Flower created with Id:"+f.getId());
    }
}
